info:
  app:
    name: Routing Datasource Example AromIT INC
    version: ${project.version}
spring:
  datasource:
    initialize: false
  aop:
    proxyTargetClass: true
datasource:
  primary-datasource:
    url: url
    driverClassName: com.mysql.jdbc.Driver
    username: username
    password: passwork
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000
  secondary-datasource:
    url: url
    driverClassName: com.mysql.jdbc.Driver
    username: username
    password: passwork
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000
  tertiary-datasource:
    url: url
    driverClassName: com.mysql.jdbc.Driver
    username: username
    password: passwork
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000
